(define-module (cart libgccjit bindings)
  #:use-module (shorthand ffi)
  #:use-module (system foreign)
  #:use-module (system foreign-library))

(define jit (dynamic-link "/usr/lib/gcc/x86_64-linux-gnu/11/libgccjit.so"))

;; I've commented out certain functions which aren't
;; defined on my version

(define-ffi jit

  ;; gccjit-docs/asm.rst.txt
  (block-add-extended-asm (ptr gcc_jit_block_add_extended_asm (ptr ptr ptr)))
  (block-end-with-extended-asm-goto (ptr gcc_jit_block_end_with_extended_asm_goto (ptr ptr ptr int ptr ptr)))
  (extended-asm-set-volatile-flag (void gcc_jit_extended_asm_set_volatile_flag (ptr int)))
  (extended-asm-set-inline-flag (void gcc_jit_extended_asm_set_inline_flag (ptr int)))
  (extended-asm-add-output-operand (void gcc_jit_extended_asm_add_output_operand (ptr ptr ptr ptr)))
  (extended-asm-add-input-operand (void gcc_jit_extended_asm_add_input_operand (ptr ptr ptr ptr)))
  (extended-asm-add-clobber (void gcc_jit_extended_asm_add_clobber (ptr ptr)))
  (extended-asm->object (ptr gcc_jit_extended_asm_as_object (ptr)))
  (context-add-top-level-asm (void gcc_jit_context_add_top_level_asm (ptr ptr ptr)))
  
  ;; gccjit-docs/compatibility.rst.txt
  (version-major (int gcc_jit_version_major ()))
  (version-minor (int gcc_jit_version_minor ()))
  (version-patchlevel (int gcc_jit_version_patchlevel ()))
  
  ;; gccjit-docs/compilation.rst.txt
  (context-compile (ptr gcc_jit_context_compile (ptr)))
  (result-get-code (ptr gcc_jit_result_get_code (ptr ptr)))
  (result-get-global (ptr gcc_jit_result_get_global (ptr ptr)))
  (result-release (void gcc_jit_result_release (ptr)))
  (context-compile-to-file (void gcc_jit_context_compile_to_file (ptr int ptr)))
  
  ;; gccjit-docs/contexts.rst.txt
  (context-acquire (ptr gcc_jit_context_acquire ()))
  (context-release (void gcc_jit_context_release (ptr)))
  (context-new-child-context (ptr gcc_jit_context_new_child_context (ptr)))
  (context-get-first-error (ptr gcc_jit_context_get_first_error (ptr)))
  (context-get-last-error (ptr gcc_jit_context_get_last_error (ptr)))
  (context-dump-to-file (void gcc_jit_context_dump_to_file (ptr ptr int)))
  (context-set-logfile (void gcc_jit_context_set_logfile (ptr ptr int int)))
  (context-dump-reproducer-to-file (void gcc_jit_context_dump_reproducer_to_file (ptr ptr)))
  (context-enable-dump (void gcc_jit_context_enable_dump (ptr ptr ptr)))
  (context-set-str-option (void gcc_jit_context_set_str_option (ptr int ptr)))
  (context-set-bool-option (void gcc_jit_context_set_bool_option (ptr int int)))
  (context-set-bool-allow-unreachable-blocks (void gcc_jit_context_set_bool_allow_unreachable_blocks (ptr int)))
  (context-set-bool-use-external-driver (void gcc_jit_context_set_bool_use_external_driver (ptr int)))
  (context-set-int-option (void gcc_jit_context_set_int_option (ptr int int)))
  (context-add-command-line-option (void gcc_jit_context_add_command_line_option (ptr ptr)))
  (context-add-driver-option (void gcc_jit_context_add_driver_option (ptr ptr)))
  
  ;; gccjit-docs/expressions.rst.txt
  (rvalue-get-type (ptr gcc_jit_rvalue_get_type (ptr)))
  (rvalue->object (ptr gcc_jit_rvalue_as_object (ptr)))
  (context-new-rvalue-from-int (ptr gcc_jit_context_new_rvalue_from_int (ptr ptr int)))
  (context-new-rvalue-from-long (ptr gcc_jit_context_new_rvalue_from_long (ptr ptr long)))
  (context-zero (ptr gcc_jit_context_zero (ptr ptr)))
  (context-one (ptr gcc_jit_context_one (ptr ptr)))
  (context-new-rvalue-from-double (ptr gcc_jit_context_new_rvalue_from_double (ptr ptr double)))
  (context-new-rvalue-from-ptr (ptr gcc_jit_context_new_rvalue_from_ptr (ptr ptr ptr)))
  (context-null (ptr gcc_jit_context_null (ptr ptr)))
  (context-new-string-literal (ptr gcc_jit_context_new_string_literal (ptr ptr)))
  ;; (context-new-array-constructor (ptr gcc_jit_context_new_array_constructor (ptr ptr ptr size_t ptr)))
  ;; (context-new-struct-constructor (ptr gcc_jit_context_new_struct_constructor (ptr ptr ptr size_t ptr ptr)))
  ;; (context-new-union-constructor (ptr gcc_jit_context_new_union_constructor (ptr ptr ptr ptr ptr)))
  (context-new-rvalue-from-vector (ptr gcc_jit_context_new_rvalue_from_vector (ptr ptr ptr size_t ptr)))
  (context-new-unary-op (ptr gcc_jit_context_new_unary_op (ptr ptr int ptr ptr)))
  (context-new-binary-op (ptr gcc_jit_context_new_binary_op (ptr ptr int ptr ptr ptr)))
  (context-new-comparison (ptr gcc_jit_context_new_comparison (ptr ptr int ptr ptr)))
  (context-new-call (ptr gcc_jit_context_new_call (ptr ptr ptr int ptr)))
  (context-new-call-through-ptr (ptr gcc_jit_context_new_call_through_ptr (ptr ptr ptr int ptr)))
  (rvalue-set-bool-require-tail-call (void gcc_jit_rvalue_set_bool_require_tail_call (ptr int)))
  (context-new-cast (ptr gcc_jit_context_new_cast (ptr ptr ptr ptr)))
  (lvalue->object (ptr gcc_jit_lvalue_as_object (ptr)))
  (lvalue->rvalue (ptr gcc_jit_lvalue_as_rvalue (ptr)))
  (lvalue-get-address (ptr gcc_jit_lvalue_get_address (ptr ptr)))
  ;; (lvalue-set-tls-model (void gcc_jit_lvalue_set_tls_model (ptr int)))
  ;; (lvalue-set-link-section (void gcc_jit_lvalue_set_link_section (ptr ptr)))
  (context-new-global (ptr gcc_jit_context_new_global (ptr ptr int ptr ptr)))
  (global-set-initializer (ptr gcc_jit_global_set_initializer (ptr ptr size_t)))
  ;; (global-set-initializer-rvalue (ptr gcc_jit_global_set_initializer_rvalue (ptr)))
  (rvalue-dereference (ptr gcc_jit_rvalue_dereference (ptr ptr)))
  (lvalue-access-field (ptr gcc_jit_lvalue_access_field (ptr ptr ptr)))
  (rvalue-access-field (ptr gcc_jit_rvalue_access_field (ptr ptr ptr)))
  (rvalue-dereference-field (ptr gcc_jit_rvalue_dereference_field (ptr ptr ptr)))
  (context-new-array-access (ptr gcc_jit_context_new_array_access (ptr ptr ptr ptr)))
  
  ;; gccjit-docs/function-pointers.rst.txt
  (function-get-address (ptr gcc_jit_function_get_address (ptr ptr)))
  (context-new-function-ptr-type (ptr gcc_jit_context_new_function_ptr_type (ptr ptr ptr int ptr int)))
  
  ;; gccjit-docs/functions.rst.txt
  (context-new-param (ptr gcc_jit_context_new_param (ptr ptr ptr ptr)))
  (param->lvalue (ptr gcc_jit_param_as_lvalue (ptr)))
  (param->rvalue (ptr gcc_jit_param_as_rvalue (ptr)))
  (param->object (ptr gcc_jit_param_as_object (ptr)))
  (context-new-function (ptr gcc_jit_context_new_function (ptr ptr int ptr ptr int ptr int)))
  (context-get-builtin-function (ptr gcc_jit_context_get_builtin_function (ptr ptr)))
  (function->object (ptr gcc_jit_function_as_object (ptr)))
  (function-get-param (ptr gcc_jit_function_get_param (ptr int)))
  (function-dump-to-dot (void gcc_jit_function_dump_to_dot (ptr ptr)))
  (function-new-local (ptr gcc_jit_function_new_local (ptr ptr ptr ptr)))
  (function-new-block (ptr gcc_jit_function_new_block (ptr ptr)))
  (block->object (ptr gcc_jit_block_as_object (ptr)))
  (block-get-function (ptr gcc_jit_block_get_function (ptr)))
  (block-add-eval (void gcc_jit_block_add_eval (ptr ptr ptr)))
  (block-add-assignment (void gcc_jit_block_add_assignment (ptr ptr ptr ptr)))
  (block-add-assignment-op (void gcc_jit_block_add_assignment_op (ptr ptr ptr int ptr)))
  (block-add-comment (void gcc_jit_block_add_comment (ptr ptr ptr)))
  (block-end-with-conditional (void gcc_jit_block_end_with_conditional (ptr ptr ptr ptr ptr)))
  (block-end-with-jump (void gcc_jit_block_end_with_jump (ptr ptr ptr)))
  (block-end-with-return (void gcc_jit_block_end_with_return (ptr ptr ptr)))
  (block-end-with-void-return (void gcc_jit_block_end_with_void_return (ptr ptr)))
  (block-end-with-switch (void gcc_jit_block_end_with_switch (ptr ptr ptr ptr int ptr)))
  (context-new-case (ptr gcc_jit_context_new_case (ptr ptr ptr ptr)))
  (case->object (ptr gcc_jit_case_as_object (ptr)))
  
  ;; gccjit-docs/locations.rst.txt
  (context-new-location (ptr gcc_jit_context_new_location (ptr ptr int int)))
  
  ;; gccjit-docs/objects.rst.txt
  (object-get-context (ptr gcc_jit_object_get_context (ptr)))
  (object-get-debug-string (ptr gcc_jit_object_get_debug_string (ptr)))
  
  ;; gccjit-docs/performance.rst.txt
  (timer-new (ptr gcc_jit_timer_new ()))
  (timer-release (void gcc_jit_timer_release (ptr)))
  (context-set-timer (void gcc_jit_context_set_timer (ptr ptr)))
  (context-get-timer (ptr gcc_jit_context_get_timer (ptr)))
  (timer-push (void gcc_jit_timer_push (ptr ptr)))
  (timer-pop (void gcc_jit_timer_pop (ptr ptr)))
  (timer-print (void gcc_jit_timer_print (ptr ptr)))
  
  ;; gccjit-docs/types.rst.txt
  (type->object (ptr gcc_jit_type_as_object (ptr)))
  (context-get-type (ptr gcc_jit_context_get_type (ptr int)))
  (context-get-int-type (ptr gcc_jit_context_get_int_type (ptr int int)))
  (type-get-pointer (ptr gcc_jit_type_get_pointer (ptr)))
  (type-get-const (ptr gcc_jit_type_get_const (ptr)))
  (type-get-volatile (ptr gcc_jit_type_get_volatile (ptr)))
  (context-new-array-type (ptr gcc_jit_context_new_array_type (ptr ptr ptr int)))
  (type-get-aligned (ptr gcc_jit_type_get_aligned (ptr size_t)))
  (type-get-vector (ptr gcc_jit_type_get_vector (ptr size_t)))
  (context-new-field (ptr gcc_jit_context_new_field (ptr ptr ptr ptr)))
  (context-new-bitfield (ptr gcc_jit_context_new_bitfield (ptr ptr ptr int ptr)))
  (field->object (ptr gcc_jit_field_as_object (ptr)))
  (context-new-struct-type (ptr gcc_jit_context_new_struct_type (ptr ptr ptr int ptr)))
  (context-new-opaque-struct (ptr gcc_jit_context_new_opaque_struct (ptr ptr ptr)))
  (struct->type (ptr gcc_jit_struct_as_type (ptr)))
  (struct-set-fields (void gcc_jit_struct_set_fields (ptr ptr int ptr)))
  (context-new-union-type (ptr gcc_jit_context_new_union_type (ptr ptr ptr int ptr))))
  ;; (type-dyncast-array (ptr gcc_jit_type_dyncast_array (ptr)))
  ;; (type-is-bool (int gcc_jit_type_is_bool (ptr)))
  ;; (type-dyncast-function-ptr-type (ptr gcc_jit_type_dyncast_function_ptr_type (ptr)))
  ;; (function-type-get-return-type (ptr gcc_jit_function_type_get_return_type (ptr)))
  ;; (function-type-get-param-count (size_t gcc_jit_function_type_get_param_count (ptr)))
  ;; (function-type-get-param-type (ptr gcc_jit_function_type_get_param_type (ptr)))
  ;; (type-is-integral (int gcc_jit_type_is_integral (ptr)))
  ;; (type-is-pointer (ptr gcc_jit_type_is_pointer (ptr)))
  ;; (type-dyncast-vector (ptr gcc_jit_type_dyncast_vector (ptr)))
  ;; (type-is-struct (ptr gcc_jit_type_is_struct (ptr)))
  ;; (vector-type-get-num-units (size_t gcc_jit_vector_type_get_num_units (ptr)))
  ;; (vector-type-get-element-type (ptr gcc_jit_vector_type_get_element_type (ptr)))
  ;; (type-unqualified (ptr gcc_jit_type_unqualified (ptr)))
  ;; (struct-get-field (ptr gcc_jit_struct_get_field (ptr)))
  ;; (struct-get-field-count (size_t gcc_jit_struct_get_field_count (ptr))))
