#include <libgccjit.h>
#include <stdio.h>
#include <string.h>

typedef struct enum_val {
  int v;
  char *n;
} enum_val;

#define PREFIX "GCC_JIT_"
#define IMPORT_STATEMENT "(define-module (cart libgccjit enums) #:use-module (guile))"

void print_enum(enum_val *ev) {
  static const unsigned long P_LEN = strlen(PREFIX);

  fputs("(define-public ", stdout);

  for (char *c = ev->n + P_LEN; *c != '\0'; c++) {
    putchar(*c == '_' ? '-' : *c);
  }

  printf(" %d)\n", ev->v);
}

#define V(A) { A , #A }

int main(void) {
  enum_val values[] = {
    V(GCC_JIT_TYPE_VOID),
    V(GCC_JIT_TYPE_VOID_PTR),
    V(GCC_JIT_TYPE_BOOL),
    V(GCC_JIT_TYPE_CHAR),
    V(GCC_JIT_TYPE_SIGNED_CHAR),
    V(GCC_JIT_TYPE_UNSIGNED_CHAR),
    V(GCC_JIT_TYPE_SHORT),
    V(GCC_JIT_TYPE_UNSIGNED_SHORT),
    V(GCC_JIT_TYPE_INT),
    V(GCC_JIT_TYPE_UNSIGNED_INT),
    V(GCC_JIT_TYPE_LONG),
    V(GCC_JIT_TYPE_UNSIGNED_LONG),
    V(GCC_JIT_TYPE_LONG_LONG),
    V(GCC_JIT_TYPE_UNSIGNED_LONG_LONG),
    V(GCC_JIT_TYPE_FLOAT),
    V(GCC_JIT_TYPE_DOUBLE),
    V(GCC_JIT_TYPE_LONG_DOUBLE),
    V(GCC_JIT_TYPE_CONST_CHAR_PTR),
    V(GCC_JIT_TYPE_SIZE_T),
    V(GCC_JIT_TYPE_FILE_PTR),
    V(GCC_JIT_TYPE_COMPLEX_FLOAT),
    V(GCC_JIT_TYPE_COMPLEX_DOUBLE),
    V(GCC_JIT_TYPE_COMPLEX_LONG_DOUBLE),

    V(GCC_JIT_FUNCTION_EXPORTED),
    V(GCC_JIT_FUNCTION_INTERNAL),
    V(GCC_JIT_FUNCTION_IMPORTED),
    V(GCC_JIT_FUNCTION_ALWAYS_INLINE),

    V(GCC_JIT_STR_OPTION_PROGNAME),

    V(GCC_JIT_BOOL_OPTION_DEBUGINFO),
    V(GCC_JIT_BOOL_OPTION_DUMP_INITIAL_TREE),
    V(GCC_JIT_BOOL_OPTION_DUMP_INITIAL_GIMPLE),
    V(GCC_JIT_BOOL_OPTION_DUMP_GENERATED_CODE),
    V(GCC_JIT_BOOL_OPTION_DUMP_SUMMARY),
    V(GCC_JIT_BOOL_OPTION_DUMP_EVERYTHING),
    V(GCC_JIT_BOOL_OPTION_SELFCHECK_GC),
    V(GCC_JIT_BOOL_OPTION_KEEP_INTERMEDIATES),

    V(GCC_JIT_INT_OPTION_OPTIMIZATION_LEVEL),

    V(GCC_JIT_UNARY_OP_MINUS),
    V(GCC_JIT_UNARY_OP_BITWISE_NEGATE),
    V(GCC_JIT_UNARY_OP_LOGICAL_NEGATE),
    V(GCC_JIT_UNARY_OP_ABS),

    V(GCC_JIT_BINARY_OP_PLUS),
    V(GCC_JIT_BINARY_OP_MINUS),
    V(GCC_JIT_BINARY_OP_MULT),
    V(GCC_JIT_BINARY_OP_DIVIDE),
    V(GCC_JIT_BINARY_OP_MODULO),
    V(GCC_JIT_BINARY_OP_BITWISE_AND),
    V(GCC_JIT_BINARY_OP_BITWISE_XOR),
    V(GCC_JIT_BINARY_OP_BITWISE_OR),
    V(GCC_JIT_BINARY_OP_LOGICAL_AND),
    V(GCC_JIT_BINARY_OP_LOGICAL_OR),
    V(GCC_JIT_BINARY_OP_LSHIFT),
    V(GCC_JIT_BINARY_OP_RSHIFT),

    V(GCC_JIT_COMPARISON_EQ),
    V(GCC_JIT_COMPARISON_NE),
    V(GCC_JIT_COMPARISON_LT),
    V(GCC_JIT_COMPARISON_LE),
    V(GCC_JIT_COMPARISON_GT),
    V(GCC_JIT_COMPARISON_GE),

#ifdef LIBGCCJIT_HAVE_gcc_jit_lvalue_set_tls_model

    V(GCC_JIT_TLS_MODEL_NONE),
    V(GCC_JIT_TLS_MODEL_GLOBAL_DYNAMIC),
    V(GCC_JIT_TLS_MODEL_LOCAL_DYNAMIC),
    V(GCC_JIT_TLS_MODEL_INITIAL_EXEC),
    V(GCC_JIT_TLS_MODEL_LOCAL_EXEC),

#endif

    V(GCC_JIT_GLOBAL_EXPORTED),
    V(GCC_JIT_GLOBAL_INTERNAL),
    V(GCC_JIT_GLOBAL_IMPORTED),

    V(GCC_JIT_OUTPUT_KIND_ASSEMBLER),
    V(GCC_JIT_OUTPUT_KIND_OBJECT_FILE),
    V(GCC_JIT_OUTPUT_KIND_DYNAMIC_LIBRARY),
    V(GCC_JIT_OUTPUT_KIND_EXECUTABLE),
  };

  printf("%s\n\n", IMPORT_STATEMENT);

  for (size_t i = 0; i < sizeof(values) / sizeof(values[0]); i++) {
    print_enum(values+i);
  }
}

