/* This code was autogenerated by gcc_jit_context_dump_reproducer_to_file.

   libgccjit (Debian 11.2.0-14) version 11.2.0 (x86_64-linux-gnu)
  	compiled by GNU C version 11.2.0, GMP version 6.2.1, MPFR version 4.1.0, MPC version 1.2.1, isl version isl-0.24-GMP

*/
#include <libgccjit.h>

#pragma GCC diagnostic ignored "-Wunused-variable"

static void
set_options (gcc_jit_context *ctxt_0x564ac78df020);

static void
create_code (gcc_jit_context *ctxt_0x564ac78df020);

int
main (int argc, const char **argv)
{
  gcc_jit_context *ctxt_0x564ac78df020;
  gcc_jit_result *result;

  ctxt_0x564ac78df020 = gcc_jit_context_acquire ();
  set_options (ctxt_0x564ac78df020);
  create_code (ctxt_0x564ac78df020);
  result = gcc_jit_context_compile (ctxt_0x564ac78df020);
  gcc_jit_context_release (ctxt_0x564ac78df020);
  gcc_jit_result_release (result);
  return 0;
}

static void
set_options (gcc_jit_context *ctxt_0x564ac78df020)
{
  /* Set options for ctxt_0x564ac78df020.  */
  /* String options.  */
  gcc_jit_context_set_str_option (ctxt_0x564ac78df020,
                                  GCC_JIT_STR_OPTION_PROGNAME,
                                  NULL);
  /* Int options.  */
  gcc_jit_context_set_int_option (ctxt_0x564ac78df020,
                                  GCC_JIT_INT_OPTION_OPTIMIZATION_LEVEL,
                                  0);
  /* Boolean options.  */
  gcc_jit_context_set_bool_option (ctxt_0x564ac78df020,
                                  GCC_JIT_BOOL_OPTION_DEBUGINFO,
                                  1);
  gcc_jit_context_set_bool_option (ctxt_0x564ac78df020,
                                  GCC_JIT_BOOL_OPTION_DUMP_INITIAL_TREE,
                                  0);
  gcc_jit_context_set_bool_option (ctxt_0x564ac78df020,
                                  GCC_JIT_BOOL_OPTION_DUMP_INITIAL_GIMPLE,
                                  0);
  gcc_jit_context_set_bool_option (ctxt_0x564ac78df020,
                                  GCC_JIT_BOOL_OPTION_DUMP_GENERATED_CODE,
                                  0);
  gcc_jit_context_set_bool_option (ctxt_0x564ac78df020,
                                  GCC_JIT_BOOL_OPTION_DUMP_SUMMARY,
                                  0);
  gcc_jit_context_set_bool_option (ctxt_0x564ac78df020,
                                  GCC_JIT_BOOL_OPTION_DUMP_EVERYTHING,
                                  0);
  gcc_jit_context_set_bool_option (ctxt_0x564ac78df020,
                                  GCC_JIT_BOOL_OPTION_SELFCHECK_GC,
                                  0);
  gcc_jit_context_set_bool_option (ctxt_0x564ac78df020,
                                  GCC_JIT_BOOL_OPTION_KEEP_INTERMEDIATES,
                                  0);
  gcc_jit_context_set_bool_allow_unreachable_blocks (ctxt_0x564ac78df020, 0);
  gcc_jit_context_set_bool_use_external_driver (ctxt_0x564ac78df020, 0);
}

static void
create_code (gcc_jit_context *ctxt_0x564ac78df020)
{
  /* Replay of API calls for ctxt_0x564ac78df020.  */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_138_10 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    138, /* int line */
    10);/* int column */
  gcc_jit_type *type_int = gcc_jit_context_get_type (ctxt_0x564ac78df020, GCC_JIT_TYPE_INT);
  gcc_jit_param *param_input =
    gcc_jit_context_new_param (ctxt_0x564ac78df020,
                               loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                               type_int, /*gcc_jit_type *type */
                               "input"); /* const char *name */
  gcc_jit_param *params_for_func_factorial[1] = {
    param_input,
  };
  gcc_jit_function *func_factorial =
    gcc_jit_context_new_function (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                  loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                  GCC_JIT_FUNCTION_EXPORTED, /* enum gcc_jit_function_kind kind */
                                  type_int, /* gcc_jit_type *return_type */
                                  "factorial", /* const char *name */
                                  1, /* int num_params */
                                  params_for_func_factorial, /* gcc_jit_param **params */
                                  0); /* int is_variadic */
  gcc_jit_type *array_type_int_16_ =
    gcc_jit_context_new_array_type (ctxt_0x564ac78df020,
                                    loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                    type_int, /* gcc_jit_type *element_type */
                                    16); /* int num_elements */
  gcc_jit_lvalue *local_stack =
    gcc_jit_function_new_local (func_factorial, /* gcc_jit_function *func */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                array_type_int_16_, /* gcc_jit_type *type */
                                "stack"); /* const char *name */
  gcc_jit_lvalue *local_idx =
    gcc_jit_function_new_local (func_factorial, /* gcc_jit_function *func */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                type_int, /* gcc_jit_type *type */
                                "idx"); /* const char *name */
  gcc_jit_lvalue *local_x =
    gcc_jit_function_new_local (func_factorial, /* gcc_jit_function *func */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                type_int, /* gcc_jit_type *type */
                                "x"); /* const char *name */
  gcc_jit_lvalue *local_y =
    gcc_jit_function_new_local (func_factorial, /* gcc_jit_function *func */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                type_int, /* gcc_jit_type *type */
                                "y"); /* const char *name */
  gcc_jit_block *block_start =
    gcc_jit_function_new_block (func_factorial, "start");
  gcc_jit_block *block_operation_0 =
    gcc_jit_function_new_block (func_factorial, "operation_0");
  gcc_jit_block_add_comment (block_operation_0, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(dup)"); /* const char *text */
  gcc_jit_block *block_operation_1 =
    gcc_jit_function_new_block (func_factorial, "operation_1");
  gcc_jit_block_add_comment (block_operation_1, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(push-const 2)"); /* const char *text */
  gcc_jit_block *block_operation_2 =
    gcc_jit_function_new_block (func_factorial, "operation_2");
  gcc_jit_block_add_comment (block_operation_2, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(binary-compare-<)"); /* const char *text */
  gcc_jit_block *block_operation_3 =
    gcc_jit_function_new_block (func_factorial, "operation_3");
  gcc_jit_block_add_comment (block_operation_3, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(jump-abs-if-true 9)"); /* const char *text */
  gcc_jit_block *block_operation_4 =
    gcc_jit_function_new_block (func_factorial, "operation_4");
  gcc_jit_block_add_comment (block_operation_4, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(dup)"); /* const char *text */
  gcc_jit_block *block_operation_5 =
    gcc_jit_function_new_block (func_factorial, "operation_5");
  gcc_jit_block_add_comment (block_operation_5, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(push-const 1)"); /* const char *text */
  gcc_jit_block *block_operation_6 =
    gcc_jit_function_new_block (func_factorial, "operation_6");
  gcc_jit_block_add_comment (block_operation_6, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(binary-subtract)"); /* const char *text */
  gcc_jit_block *block_operation_7 =
    gcc_jit_function_new_block (func_factorial, "operation_7");
  gcc_jit_block_add_comment (block_operation_7, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(recur)"); /* const char *text */
  gcc_jit_block *block_operation_8 =
    gcc_jit_function_new_block (func_factorial, "operation_8");
  gcc_jit_block_add_comment (block_operation_8, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(binary-multiply)"); /* const char *text */
  gcc_jit_block *block_operation_9 =
    gcc_jit_function_new_block (func_factorial, "operation_9");
  gcc_jit_block_add_comment (block_operation_9, /*gcc_jit_block *block */
                             loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                             "(return)"); /* const char *text */
  gcc_jit_rvalue *rvalue__int_0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          0L); /* long value */
  gcc_jit_block_add_assignment (block_start, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue__int_0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx_ = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_138_10, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_start, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                lvalue_stack_idx_, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_param_as_rvalue (param_input)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_start, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_start, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                               block_operation_0); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_139_11 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    139, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f7a90 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78a4e10 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f7a90); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_0, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78a4e10); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f7b30 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_139_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_0, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                local_x, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78f7b30)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f7be0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_139_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_0, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78f7be0, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (local_x)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f7c90 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f7ce0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f7c90); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_0, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f7ce0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f7de0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_139_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_0, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78f7de0, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (local_x)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f7e90 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f7ee0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f7e90); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_0, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f7ee0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_operation_0, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_139_11, /* gcc_jit_location *loc */
                               block_operation_1); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_140_11 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    140, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_2 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          2L); /* long value */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f7740 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_140_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_1, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_140_11, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78f7740, /* gcc_jit_lvalue *lvalue */
                                rvalue__int_2); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f8660 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f86b0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_140_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f8660); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_1, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_140_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f86b0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_operation_1, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_140_11, /* gcc_jit_location *loc */
                               block_operation_2); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_141_11 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    141, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f8840 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f8890 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f8840); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_2, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f8890); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f8940 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_141_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_2, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                local_x, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78f8940)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f89f0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f8a40 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f89f0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_2, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f8a40); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f8af0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_141_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_2, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                local_y, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78f8af0)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_type *type_bool = gcc_jit_context_get_type (ctxt_0x564ac78df020, GCC_JIT_TYPE_BOOL);
  gcc_jit_rvalue *rvalue_y___x =
    gcc_jit_context_new_comparison (ctxt_0x564ac78df020,
                                    loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                    GCC_JIT_COMPARISON_LT, /* enum gcc_jit_comparison op */
                                    gcc_jit_lvalue_as_rvalue (local_y), /* gcc_jit_rvalue *a */
                                    gcc_jit_lvalue_as_rvalue (local_x)); /* gcc_jit_rvalue *b */
  gcc_jit_rvalue *rvalue__int__y___x_ =
    gcc_jit_context_new_cast (ctxt_0x564ac78df020,
                              loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                              rvalue_y___x, /* gcc_jit_rvalue *rvalue */
                              type_int); /* gcc_jit_type *type */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f8ce0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_141_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_2, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78f8ce0, /* gcc_jit_lvalue *lvalue */
                                rvalue__int__y___x_); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f8d90 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f8de0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f8d90); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_2, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f8de0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_operation_2, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_141_11, /* gcc_jit_location *loc */
                               block_operation_3); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_142_11 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    142, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f8f80 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f8fd0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_142_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f8f80); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_3, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_142_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f8fd0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f9080 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_142_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_3, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_142_11, /* gcc_jit_location *loc */
                                local_x, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78f9080)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_0_0x564ac78f9130 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          0L); /* long value */
  gcc_jit_rvalue *rvalue_x_____int_0 =
    gcc_jit_context_new_comparison (ctxt_0x564ac78df020,
                                    loc_cart_oop_examples_part4_scm_142_11, /* gcc_jit_location *loc */
                                    GCC_JIT_COMPARISON_EQ, /* enum gcc_jit_comparison op */
                                    gcc_jit_lvalue_as_rvalue (local_x), /* gcc_jit_rvalue *a */
                                    rvalue__int_0_0x564ac78f9130); /* gcc_jit_rvalue *b */
  gcc_jit_block_end_with_conditional (block_operation_3, /*gcc_jit_block *block */
                                      loc_cart_oop_examples_part4_scm_142_11, /* gcc_jit_location *loc */
                                      rvalue_x_____int_0, /* gcc_jit_rvalue *boolval */
                                      block_operation_4, /* gcc_jit_block *on_true */
                                      block_operation_9); /* gcc_jit_block *on_false */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    139, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f98d0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f9920 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f98d0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_4, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f9920); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f99d0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_4, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                local_x, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78f99d0)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f9b20 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_4, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78f9b20, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (local_x)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f9bd0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f9c20 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f9bd0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_4, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f9c20); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f9d20 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_4, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78f9d20, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (local_x)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f9dd0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f9e40 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f9dd0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_4, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f9e40); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_operation_4, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_139_11_0x564ac78f9890, /* gcc_jit_location *loc */
                               block_operation_5); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_140_11_0x564ac78f9fa0 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    140, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f9aa0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f9fe0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_140_11_0x564ac78f9fa0, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_5, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_140_11_0x564ac78f9fa0, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78f9fe0, /* gcc_jit_lvalue *lvalue */
                                rvalue__int_1_0x564ac78f9aa0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78fa110 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78fa160 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_140_11_0x564ac78f9fa0, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78fa110); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_5, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_140_11_0x564ac78f9fa0, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78fa160); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_operation_5, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_140_11_0x564ac78f9fa0, /* gcc_jit_location *loc */
                               block_operation_6); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_145_11 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    145, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78fa2e0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78fa330 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78fa2e0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_6, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78fa330); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78fa3e0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_145_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_6, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                local_x, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78fa3e0)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78fa490 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78fa4e0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78fa490); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_6, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78fa4e0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78fa590 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_145_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_6, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                local_y, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78fa590)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue_y___x_0x564ac78fa690 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_y), /* gcc_jit_rvalue *a */
                                   gcc_jit_lvalue_as_rvalue (local_x)); /* gcc_jit_rvalue *b */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78fa6f0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_145_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_6, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78fa6f0, /* gcc_jit_lvalue *lvalue */
                                rvalue_y___x_0x564ac78fa690); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78fa7a0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78fa7f0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78fa7a0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_6, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78fa7f0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_operation_6, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_145_11, /* gcc_jit_location *loc */
                               block_operation_7); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_146_11 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    146, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78fa990 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78fa9e0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_146_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78fa990); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_7, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_146_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78fa9e0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78faa90 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_146_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_7, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_146_11, /* gcc_jit_location *loc */
                                local_x, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78faa90)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *args_for__call_factorial__x_[1] = {
    gcc_jit_lvalue_as_rvalue (local_x),
  };
  gcc_jit_rvalue *call_factorial__x_ =
    gcc_jit_context_new_call (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                              loc_cart_oop_examples_part4_scm_146_11, /* gcc_jit_location *loc */
                              func_factorial, /* gcc_jit_function *func */
                              1, /* int numargs  */ 
                              args_for__call_factorial__x_); /* gcc_jit_rvalue **args*/
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78fab10 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_146_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_7, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_146_11, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78fab10, /* gcc_jit_lvalue *lvalue */
                                call_factorial__x_); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78facc0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78fad10 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_146_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78facc0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_7, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_146_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78fad10); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_operation_7, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_146_11, /* gcc_jit_location *loc */
                               block_operation_8); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_147_11 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    147, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f9310 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f9360 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f9310); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_8, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f9360); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f9410 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_147_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_8, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                local_x, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78f9410)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78f94c0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78f9510 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78f94c0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_8, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78f9510); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78f95c0 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_147_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_8, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                local_y, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78f95c0)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue_y___x_0x564ac78f96c0 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MULT, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_y), /* gcc_jit_rvalue *a */
                                   gcc_jit_lvalue_as_rvalue (local_x)); /* gcc_jit_rvalue *b */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78fb600 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_147_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_8, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                lvalue_stack_idx__0x564ac78fb600, /* gcc_jit_lvalue *lvalue */
                                rvalue_y___x_0x564ac78f96c0); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78fb6b0 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78fb700 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_PLUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78fb6b0); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_8, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78fb700); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_jump (block_operation_8, /*gcc_jit_block *block */
                               loc_cart_oop_examples_part4_scm_147_11, /* gcc_jit_location *loc */
                               block_operation_9); /* gcc_jit_block *target */
  gcc_jit_location *loc_cart_oop_examples_part4_scm_148_11 =
    gcc_jit_context_new_location (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
    "cart/oop/examples/part4.scm", /* const char *filename */
    148, /* int line */
    11);/* int column */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78fb920 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_rvalue *rvalue_idx____int_1_0x564ac78fb970 =
    gcc_jit_context_new_binary_op (ctxt_0x564ac78df020,
                                   loc_cart_oop_examples_part4_scm_148_11, /* gcc_jit_location *loc */
                                   GCC_JIT_BINARY_OP_MINUS, /* enum gcc_jit_binary_op op */
                                   type_int, /* gcc_jit_type *result_type */
                                   gcc_jit_lvalue_as_rvalue (local_idx), /* gcc_jit_rvalue *a */
                                   rvalue__int_1_0x564ac78fb920); /* gcc_jit_rvalue *b */
  gcc_jit_block_add_assignment (block_operation_9, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_148_11, /* gcc_jit_location *loc */
                                local_idx, /* gcc_jit_lvalue *lvalue */
                                rvalue_idx____int_1_0x564ac78fb970); /* gcc_jit_rvalue *rvalue */
  gcc_jit_lvalue *lvalue_stack_idx__0x564ac78fba20 = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_148_11, /*gcc_jit_location *loc */
                                      gcc_jit_lvalue_as_rvalue (local_stack), /* gcc_jit_rvalue *ptr */
                                      gcc_jit_lvalue_as_rvalue (local_idx)); /* gcc_jit_rvalue *index */
  gcc_jit_block_add_assignment (block_operation_9, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_148_11, /* gcc_jit_location *loc */
                                local_x, /* gcc_jit_lvalue *lvalue */
                                gcc_jit_lvalue_as_rvalue (lvalue_stack_idx__0x564ac78fba20)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_block_end_with_return (block_operation_9, /*gcc_jit_block *block */
                                 loc_cart_oop_examples_part4_scm_148_11, /* gcc_jit_location *loc */
                                 gcc_jit_lvalue_as_rvalue (local_x)); /* gcc_jit_rvalue *rvalue */
  gcc_jit_param *param_argc =
    gcc_jit_context_new_param (ctxt_0x564ac78df020,
                               loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                               type_int, /*gcc_jit_type *type */
                               "argc"); /* const char *name */
  gcc_jit_type *type_const_char__ = gcc_jit_context_get_type (ctxt_0x564ac78df020, GCC_JIT_TYPE_CONST_CHAR_PTR);
  gcc_jit_type *type_const_char____ =
    gcc_jit_type_get_pointer (type_const_char__);
  gcc_jit_param *param_argv =
    gcc_jit_context_new_param (ctxt_0x564ac78df020,
                               loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                               type_const_char____, /*gcc_jit_type *type */
                               "argv"); /* const char *name */
  gcc_jit_param *params_for_func_main[2] = {
    param_argc,
    param_argv,
  };
  gcc_jit_function *func_main =
    gcc_jit_context_new_function (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                  loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                  GCC_JIT_FUNCTION_EXPORTED, /* enum gcc_jit_function_kind kind */
                                  type_int, /* gcc_jit_type *return_type */
                                  "main", /* const char *name */
                                  2, /* int num_params */
                                  params_for_func_main, /* gcc_jit_param **params */
                                  0); /* int is_variadic */
  gcc_jit_block *block__f =
    gcc_jit_function_new_block (func_main, "#f");
  gcc_jit_param *param_nptr =
    gcc_jit_context_new_param (ctxt_0x564ac78df020,
                               loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                               type_const_char__, /*gcc_jit_type *type */
                               "nptr"); /* const char *name */
  gcc_jit_param *params_for_func_atoi[1] = {
    param_nptr,
  };
  gcc_jit_function *func_atoi =
    gcc_jit_context_new_function (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                  loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                  GCC_JIT_FUNCTION_IMPORTED, /* enum gcc_jit_function_kind kind */
                                  type_int, /* gcc_jit_type *return_type */
                                  "atoi", /* const char *name */
                                  1, /* int num_params */
                                  params_for_func_atoi, /* gcc_jit_param **params */
                                  0); /* int is_variadic */
  gcc_jit_param *param_fmt =
    gcc_jit_context_new_param (ctxt_0x564ac78df020,
                               loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                               type_const_char__, /*gcc_jit_type *type */
                               "fmt"); /* const char *name */
  gcc_jit_param *params_for_func_printf[1] = {
    param_fmt,
  };
  gcc_jit_function *func_printf =
    gcc_jit_context_new_function (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                  loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                  GCC_JIT_FUNCTION_IMPORTED, /* enum gcc_jit_function_kind kind */
                                  type_int, /* gcc_jit_type *return_type */
                                  "printf", /* const char *name */
                                  1, /* int num_params */
                                  params_for_func_printf, /* gcc_jit_param **params */
                                  1); /* int is_variadic */
  gcc_jit_lvalue *local_in =
    gcc_jit_function_new_local (func_main, /* gcc_jit_function *func */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                type_int, /* gcc_jit_type *type */
                                "in"); /* const char *name */
  gcc_jit_rvalue *rvalue__int_1_0x564ac78fc150 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          1L); /* long value */
  gcc_jit_lvalue *lvalue_argv__int_1_ = 
    gcc_jit_context_new_array_access (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                      loc_cart_oop_examples_part4_scm_138_10, /*gcc_jit_location *loc */
                                      gcc_jit_param_as_rvalue (param_argv), /* gcc_jit_rvalue *ptr */
                                      rvalue__int_1_0x564ac78fc150); /* gcc_jit_rvalue *index */
  gcc_jit_rvalue *args_for__call_atoi__argv__int_1__[1] = {
    gcc_jit_lvalue_as_rvalue (lvalue_argv__int_1_),
  };
  gcc_jit_rvalue *call_atoi__argv__int_1__ =
    gcc_jit_context_new_call (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                              loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                              func_atoi, /* gcc_jit_function *func */
                              1, /* int numargs  */ 
                              args_for__call_atoi__argv__int_1__); /* gcc_jit_rvalue **args*/
  gcc_jit_block_add_assignment (block__f, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                local_in, /* gcc_jit_lvalue *lvalue */
                                call_atoi__argv__int_1__); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *args_for__call_factorial__in_[1] = {
    gcc_jit_lvalue_as_rvalue (local_in),
  };
  gcc_jit_rvalue *call_factorial__in_ =
    gcc_jit_context_new_call (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                              loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                              func_factorial, /* gcc_jit_function *func */
                              1, /* int numargs  */ 
                              args_for__call_factorial__in_); /* gcc_jit_rvalue **args*/
  gcc_jit_block_add_assignment (block__f, /*gcc_jit_block *block */
                                loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                local_in, /* gcc_jit_lvalue *lvalue */
                                call_factorial__in_); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__result___d_n_ =
    gcc_jit_context_new_string_literal (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                        "result: %d\n"); /* const char *value */
  gcc_jit_rvalue *args_for__call_printf___result___d_n___in_[2] = {
    rvalue__result___d_n_,
    gcc_jit_lvalue_as_rvalue (local_in),
  };
  gcc_jit_rvalue *call_printf___result___d_n___in_ =
    gcc_jit_context_new_call (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                              loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                              func_printf, /* gcc_jit_function *func */
                              2, /* int numargs  */ 
                              args_for__call_printf___result___d_n___in_); /* gcc_jit_rvalue **args*/
  gcc_jit_block_add_eval (block__f, /*gcc_jit_block *block */
                          loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                          call_printf___result___d_n___in_); /* gcc_jit_rvalue *rvalue */
  gcc_jit_rvalue *rvalue__int_0_0x564ac78fc590 =
    gcc_jit_context_new_rvalue_from_long (ctxt_0x564ac78df020, /* gcc_jit_context *ctxt */
                                          type_int, /* gcc_jit_type *numeric_type */
                                          0L); /* long value */
  gcc_jit_block_end_with_return (block__f, /*gcc_jit_block *block */
                                 loc_cart_oop_examples_part4_scm_138_10, /* gcc_jit_location *loc */
                                 rvalue__int_0_0x564ac78fc590); /* gcc_jit_rvalue *rvalue */
}
